version: 2.1
orbs:
  snyk: snyk/snyk@1.0.1
jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    resource_class: small
    steps:
      - checkout
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
  run_tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
workflows:
  build_and_test:
    jobs:
      - build
      - approve-test:
          type: approval
          requires:
            - build
      - run_tests:
          requires:
            - approve-test
